---
- name: Deploy ubuntu desktop Environment
  hosts: local
  roles:
    - role: geerlingguy.swap
      swap_file_size_mb: '4096'
      become: yes
    - role: geerlingguy.ntp
      ntp_timezone: Asia/Hong_Kong
      become: yes
    - role: andrewrothstein.atom
    - role: base-desktop
      become: yes
    - role: avanov.pyenv
  vars:
    ENV: local
