---
- name: Deploy Kail Desktop ENVIRONMENT
  hosts: development
  gather_facts: false
  roles:
    - role: geerlingguy.swap
      swap_file_size_mb: '4096'
      become: yes
    - role: geerlingguy.ntp
      ntp_timezone: Asia/Hong_Kong
      become: yes
    # - role: raspberry_pi
    #   become: yes
    #   when:
    #     - raspberry_pi_with_lcd
  vars:
    ENV: development
