 - src: geerlingguy.swap
   version: 1.0.0
 - src: geerlingguy.ntp
   version: 1.6.2
 - src: andrewrothstein.atom
   version: v1.2.1
 - src: wtanaka.gimp
   version: master
 - src: wtanaka.slack
   version: master
 - src: ucsdlib.libreoffice
   version: 1.1.0
