 - src: geerlingguy.swap
   version: 1.0.0
 - src: geerlingguy.ntp
   version: 1.6.2
 - src: andrewrothstein.atom
   version: v1.2.1
 - src: wtanaka.gimp
   version: master
 - src: wtanaka.slack
   version: master
 - src: ucsdlib.libreoffice
   version: 1.1.0
 - src: avanov.pyenv
   version: b71c95c9fe2d9faa46cac4b76e9eb2d646a3947a
