---
- name: Install list of packages
  apt:
   name: "{{item}}"
   state: installed
  with_items:
       - git
       - build-essential
       - fcitx-table-cangjie3
       - preload
       - gimp
       - openssh-server
       - mysql-workbench

- name: install chrome
  include: chrome.yml
